---
title: "Getting started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Installation

## 1. Installer R
R est le langage de programmation utilisé pour ce projet. Il est nécessaire d'installer R pour pouvoir exécuter le code.  
Téléchargez et installez R pour votre système d'exploitation en suivant les instructions officielles.  
[Télécharger et installer R](https://cran.rstudio.com/)

## 2. Installer RStudio IDE
RStudio est un environnement de développement intégré (IDE) pour R. Il est recommandé d'utiliser RStudio pour travailler sur ce projet, mais un autre IDE peut être utilisé.  
Téléchargez et installez RStudio pour votre système d'exploitation en suivant les instructions officielles.  
[Télécharger et installer RStudio](https://posit.co/download/rstudio-desktop/)

## 3. Installer Git 
Git est un système de contrôle de version et de travail en parallèle pour les projets informatiques. Grâce à cet outil, il est possible de recevoir les mises à jours du code, suivre l'historique des modifications, effectuer des modifications sans risque de modifier le code original, créer des sous-projets paralèlle pour chaque banque, etc.  
Télécharger et installer Git pour votre système d'exploitation en suivant les instructions officielles.  
[Télécharger et installer Git](https://git-scm.com/downloads)  

::: {.alert .alert-primary}
**NOTE**  
Pour Windows, téléchargez le `64-bit Git for Windows Setup`. Durant l'installation, toutes les étapes de personnalisation peuvent être passées et laissées par défaut.
::: 

## 4. Télécharger le projet localement
1. Ouvrez RStudio
2. Dans la barre de menu, cliquez sur `File` > `New Project...` > `Version Control` > `Git`
3. Entrez l'URL du projet Git : `https://github.com/maximecharriere/BuildingsEmissionsCalculator.git` et l'emplacelement local où vous souhaitez enregistrer le projet
4. Cliquez sur `Create Project`. Afin de garantir la sécurité du projet, il vous sera demandé de vous connecter à GitHub. Choisisez l'option `Sign in with your browser`, et connectez vous. Si vous n'avez pas de compte, créez-en un, et demandez à un auteur du projet de vous ajouter en tant que collaborateur.
5. Le projet est maintenant téléchargé localement. Vous pouvez le retrouver dans l'onglet `Files` de RStudio. Vous devriez voir l'info suivante dans la console:  
  ```
  - Project '~/BuildingsEmissionsCalculator' loaded. [renv 1.0.9]
  - One or more packages recorded in the lockfile are not installed.
  - Use `renv::status()` for more details.
  ```

## 5. Installer les packages
Dans la `Console` de RStudio, exécutez la commande `renv::restore()`. Cela installera tous les packages nécessaires et peut prendre plusieurs minutes.  
Si un message s'affiche du type `The following package(s) will be updated:... Do you want to proceed? [Y/n]:`, répondez `Y`.

## 6. Télécharger la base de données du RegBL
Si vous n'avez pas déjà la base de données du RegBL sous `./data/regbl_db.sqlite`, exécutez les commandes suivantes dans la `Console` de RStudio. Le téléchargement et l'extraction peut prendre plusieurs minutes (2-10min):   
```
devtools::load_all(".")
BuildingsEmissionsCalculator::download_regbl_db("./data/regbl_db.sqlite")
```

# Utilisation

1. Ouvrer le projet R `BuildingsEmissionsCalculator.Rproj` dans RStudio (double clic sur le fichier depuis Windows Explorer).
2. Dans la fenêtre `File` (en bas à droite), un script d'utilisation est disponible dans le fichier `./scripts/main.R`.
3. Copier le template avec la dernière version présent sous `template/template_<version>.xlsx` dans votre dossier de travail.
4. Remplissez le fichier Excel avec les données de votre banque.
5. Dans la section `Parameters` du code, ajustez les paramètres selon vos besoins. Vous pouvez soit mettre `INTERACTIVE <- FALSE` et écrire la chemin de votre fichier Excel directement dans le code, soit mettre `INTERACTIVE <- TRUE`, ce qui vous permettra de choisir le fichier Excel à traiter à chaque exécution via un explorateur de fichiers. Il est aussi conseillé de mettre une petite valeur de `max_rows` pour tester le code dans un premier temps, puis de mettre à `-1` pour traiter l'ensemble des données, uniquement lorsque vous êtes sûr que le code fonctionne correctement.
6. Pressez le bouton `Source` en haut à droite de la fenêtre du script pour exécuter le code. Le fichier rempli sera enregistré au même emplacement que le fichier Excel original, avec le suffixe `_filled` ajouté au nom du fichier.

# Modification du code
Il est recommendé d'utiliser Git pour gérer les modifications du code.  
TODO: Ajouter des instructions pour Git et les modifications du code.
